# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
import cv2
import keras
import numpy as np

model = keras.models.load_model("FaceMaskdetector.keras")


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 100, 131, 16))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(60, 120, 271, 21))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Mask Detection Algorithm"))
        self.label.setText(_translate("Dialog", "Enter Image Path"))
        self.buttonBox.clicked.connect(self.clickme)


    def predictor(self,path):
        image = cv2.imread(path)
        image = cv2.resize(image, dsize=(128, 128))
        image = np.expand_dims(image, 0)
        result = model.predict(image)
        if(result[0][0] == max(result[0][0],result[0][1])):
            print("Mask Found")
            return "Mask Found"
        else:
            print("Mask Not found")
            return "Mask not Found"
    def clickme(self):
        msg = QtWidgets.QMessageBox()
        path = self.textEdit.toPlainText()
        path = r'{}'.format(path)
        result = self.predictor(path)


        # setting message for Message Box
        msg.setText(result)

        # setting Message box window title
        msg.setWindowTitle("Result")

        # declaring buttons on Message Box

        msg.exec_()
        sys.exit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
